apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19-news-deployment
  labels:
    app: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: covid19-news-be
          image: denisduev/covid-19:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot
spec:
  selector:
    app: spring-boot
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer